export {
  getApiCatalog,
  searchApiCatalog,
  summarizeApiCatalog,
  type ApiCatalog,
  type ApiEntryPoint,
  type ApiExport,
  type ApiMember,
  type ApiPackage,
  type ApiSearchResult,
} from "./catalog.js";
export {
  COMPONENTS,
  DATA_SHAPE_FORMATS,
  DATA_TIME_UNITS,
  diagnoseChart,
  FRAMEWORKS,
  generateIntegration,
  RENDER_MODES,
  recommendPackages,
  recommendPerformanceSettings,
  validateChartOptions,
  type ChartRenderMode,
  type ComponentKind,
  type DataShapeDescription,
  type DataShapeFormat,
  type DataTimeUnit,
  type FrameworkKind,
  type IntegrationRecipe,
  type OptionsValidation,
  type PackageRecommendation,
  type PerformanceRecommendation,
} from "./guidance.js";
